version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    commit-message:
      prefix: "[lib]"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      vercel:
        patterns:
          - "@vercel/*"
